config/routes.rb
Rails.application.routes.draw do
  resources :movies
  root :to => redirect('/movies')
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/movie.rb
class Movie < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: %i[ show edit update destroy ]

  # GET /movies or /movies.json
  def index
    session[:sort_by] = params[:sort_by] if params[:sort_by]
    session[:direction] = params[:direction] if params[:direction]

    @sort_column = session[:sort_by] || 'title'
    @sort_direction = %w[asc desc].include?(session[:direction]) ? session[:direction] : 'asc'
    @movies = Movie.order("#{@sort_column} #{@sort_direction}")
  end


  # GET /movies/1 or /movies/1.json
  def show
  end

  # GET /movies/new
  def new
    @movie = Movie.new
  end

  # GET /movies/1/edit
  def edit
  end

  # POST /movies or /movies.json
  def create
    @movie = Movie.new(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to movie_url(@movie), notice: "Movie was successfully created." }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1 or /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to movie_url(@movie), notice: "Movie was successfully updated." }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1 or /movies/1.json
  def destroy
    @movie.destroy!

    respond_to do |format|
      format.html { redirect_to movies_url, notice: "Movie was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def movie_params
      params.require(:movie).permit(:title, :rating, :description, :release_date)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
    def toggle_direction(column)
      column == session[:sort_by] && session[:direction] == "asc" ? "desc" : "asc"
    end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rottenpotatoes</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/movies/_form.html.erb
<%= form_with(model: movie) do |form| %>
  <% if movie.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
        <% movie.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :rating, style: "display: block" %>
    <%= form.text_field :rating %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.label :release_date, style: "display: block" %>
    <%= form.text_field :release_date %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/movies/_movie.html.erb
<div id="<%= dom_id movie %>">
  <p>
    <strong>Title:</strong>
    <%= movie.title %>
  </p>

  <p>
    <strong>Rating:</strong>
    <%= movie.rating %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= movie.description %>
  </p>

  <p>
    <strong>Release date:</strong>
    <%= movie.release_date %>
  </p>

</div>

app/views/movies/edit.html.erb
<h1>Editing movie</h1>

<%= render "form", movie: @movie %>

<br>

<div>
  <%= link_to "Show this movie", @movie %> |
  <%= link_to "Back to movies", movies_path %>
</div>

app/views/movies/index.html.erb
<h1>Movies</h1>

<table>
  <thead>
  <tr>
    <th class="<%= 'sorted-asc' if @sort_column == 'title' && @sort_direction == 'asc' %>
               <%= 'sorted-desc' if @sort_column == 'title' && @sort_direction == 'desc' %>">
      <%= link_to "Title", movies_path(sort_by: 'title', direction: toggle_direction('title')), id: 'title_header' %>
    </th>
    <th class="<%= 'sorted-asc' if @sort_column == 'rating' && @sort_direction == 'asc' %>
               <%= 'sorted-desc' if @sort_column == 'rating' && @sort_direction == 'desc' %>">
      <%= link_to "Rating", movies_path(sort_by: 'rating', direction: toggle_direction('rating')), id: 'rating_header' %>
    </th>
    <th class="<%= 'sorted-asc' if @sort_column == 'release_date' && @sort_direction == 'asc' %>
               <%= 'sorted-desc' if @sort_column == 'release_date' && @sort_direction == 'desc' %>">
      <%= link_to "Release Date", movies_path(sort_by: 'release_date', direction: toggle_direction('release_date')), id: 'release_date_header' %>
    </th>
  </tr>
  </thead>


  <tbody>
  <% @movies.each do |movie| %>
    <tr>
      <td><%= movie.title %></td>
      <td><%= movie.rating %></td>
      <td><%= movie.release_date.strftime('%Y-%m-%d') %></td> <!-- Format the date -->
    </tr>
  <% end %>
  </tbody>

  <tfoot>
  <tr>
    <td colspan="3">Total Movies: <%= @movies.count %></td>
  </tr>
  </tfoot>
</table>

<%= link_to 'New movie', new_movie_path %>

<style>
    /* Style for highlighting sorted column headers */
    .sorted-asc, .sorted-desc {
        font-weight: bold;
        color: #4CAF50; /* Green color for visual cue */
    }
    .sorted-desc {
        color: #F44336; /* Red color for reverse sorting */
    }
    /* Add a symbol for the sorted column */
    .sorted-asc:after {
        content: " \2191"; /* Upward arrow for ascending sort */
    }
    .sorted-desc:after {
        content: " \2193"; /* Downward arrow for descending sort */
    }
    /* Additional styling */
    table {
        width: 100%;
        border-collapse: collapse;
    }
    th, td {
        border: 1px solid #ddd;
        padding: 8px;
        text-align: left;
    }
    th {
        background-color: #f2f2f2;
    }
</style>

app/views/movies/new.html.erb
<h1>New movie</h1>

<%= render "form", movie: @movie %>

<br>

<div>
  <%= link_to "Back to movies", movies_path %>
</div>

app/views/movies/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @movie %>

<div>
  <%= link_to "Edit this movie", edit_movie_path(@movie) %> |
  <%= link_to "Back to movies", movies_path %>

  <%= button_to "Destroy this movie", @movie, method: :delete %>
</div>